import classNames from 'classnames';
import React from 'react';

import {
  AbuseDetection,
  Button,
  EntitiesRecognition,
  Sentiment,
  SpamDetection,
  ToneRecognition,
  Typography,
} from '~/components';
import {SocialMedia} from '~/constants';

import styles from './Discover.module.scss';
import {DiscoverContainerProps} from './types';

const DiscoverContainer: React.FC<DiscoverContainerProps> = ({containerRef}) => {
  const socialClasses = (type: string): string =>
    classNames(styles.container__content_social_item, {
      [styles.container__content_social_item_soon]: type === 'Coming soon!',
    });

  const renderSocialMedia = SocialMedia.map(({Icon, id, name, type}) => (
    <div key={id} className={socialClasses(type)}>
      <div className={styles.container__content_social_item_right}>
        <Icon />
        <Typography className={styles.container__content_social_item_right_text}>{name}</Typography>
      </div>
      <div>
        <Typography>{type}</Typography>
      </div>
    </div>
  ));

  return (
    <div ref={containerRef} className={styles.container}>
      <Typography isQuestion className={styles.container__title}>
        Discover the key Insights
      </Typography>
      <div className={styles.container__content}>
        <div className={styles.container__content_left}>
          <Sentiment />
          <ToneRecognition />
        </div>
        <div className={styles.container__content_right}>
          <AbuseDetection />
          <EntitiesRecognition />
          <SpamDetection />
        </div>
      </div>
      <div className={styles.container__content_social}>
        <Typography className={styles.container__content_social_title} isQuestion>
          Social media displaying
        </Typography>

        <div className={styles.container__content_social_item_wrapper}>{renderSocialMedia}</div>

        <div className={styles.container__content_integrate}>
          <Typography className={styles.container__content_integrate__title}>
            Integrate TrueFilter into your product using our brand new TrueFilter API
          </Typography>
          <Typography className={styles.container__content_integrate__subtitle}>
            Some secondary text will be generated by Matthew
          </Typography>
          <Button className={styles.container__content_integrate__button}>Learn more</Button>
        </div>
      </div>
    </div>
  );
};

export default DiscoverContainer;
